name: Build and Deploy Static Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Gerar build estático
        run: npm run build

      - name: Publicar na branch deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./out
          force_orphan: true
